# -*- coding: utf-8 -*-
# ext building script
#

Import('genv')

env = genv.Clone()

env["CCFLAGS"] = [
    "-O3",
    "-g",
    #"-DSYS_DEBUG",
]

dst = "lua"

inc = [
    ".",
]

src_luac = [
     "luac.c",
]

src_lua = [
     "lua.c",
]


src_core = [
	"lapi.c", 
	"lcode.c", 
	"lctype.c", 
	"ldebug.c", 
	"ldo.c", 
	"ldump.c", 
	"lfunc.c", 
	"lgc.c", 
	"llex.c", 
	"lmem.c", 
	"lobject.c", 
	"lopcodes.c", 
	"lparser.c", 
	"lstate.c", 
	"lstring.c", 
	"ltable.c", 
	"ltm.c", 
	"lundump.c", 
	"lvm.c", 
	"lzio.c",
]

src_lib = [
	"lauxlib.c",
	"lbaselib.c",
	"lbitlib.c",
	"lcorolib.c",
	"ldblib.c",
	"liolib.c",
	"lmathlib.c",
	"loslib.c",
	"lstrlib.c",
	"ltablib.c",
	"lutf8lib.c",
	"loadlib.c",
	"linit.c",
]

src = src_core
src += src_lib

lib = [
]

env["LIBPATH"] = [
    genv["out"],
]

env["LINKFLAGS"] = [
    "",
]

if genv["BUILD_PLATFORM"] == "win":
    env["LINKFLAGS"] = [
        "-static-libgcc",
    ]
    #env["CCFLAGS"] += ["-DLUA_BUILD_AS_DLL"]
    lib += []
else:
   env["CCFLAGS"] += ["-DLUA_USE_LINUX"]
   lib += ["dl", "readline"]

lib_exe = lib;
lib_exe += ["lua"] 
  
lua_static = env.StaticLibrary(target=dst, source=src, LIBS=lib, CPPPATH=inc)
lua_exe = env.Program(target="lua", source=src_lua, LIBS=lib_exe, CPPPATH=inc)
luac_exe = env.Program(target="luac", source=src_luac, LIBS=lib_exe, CPPPATH=inc)
Return("lua_static", "lua_exe", "luac_exe")
